VERSION: 1.0.0.1
GPLOAD:
  INPUT:
    - SOURCE:
       FILE:
         - ${data_directory}/Product_Dimension.tbl
    - FORMAT: text
    - DELIMITER: '|'
    - NULL_AS: ''
    - ENCODING: UTF8
    - ERROR_LIMIT: 1000
    - LOG_ERRORS: true
  OUTPUT:
    - TABLE: Product_Dimension
    - MODE: insert
  PRELOAD:
    - REUSE_TABLES: true
    - TRUNCATE: true